import { BridgeContextResponse, CrossDomainBridgeItem } from '../api/graph';

export interface ExportSynthesisData {
  summary?: string;
  practicalImplications?: string[];
  bridgeExplanations?: Record<string, string>; // bridge_id -> explanation text
}

export function buildConstellationMarkdown(
  context: BridgeContextResponse,
  synthesis?: ExportSynthesisData
): string {
  const currentDate = new Date().toISOString().split('T')[0];
  const uniqueSources = new Map<string, string>();

  // Сбор уникальных первоисточников
  context.top_bridges.forEach((b) => {
    uniqueSources.set(b.source_claim.source_id, b.source_claim.source_title);
    uniqueSources.set(b.target_claim.source_id, b.target_claim.source_title);
  });

  const lines: string[] = [];

  // YAML Frontmatter для совместимости с Obsidian / Hugo / Zettelkasten
  lines.push('---');
  lines.push('type: cross-domain-analysis');
  lines.push(`domains:`);
  lines.push(`  - "${context.domain_a}"`);
  lines.push(`  - "${context.domain_b}"`);
  lines.push(`date: ${currentDate}`);
  lines.push(`generator: PKA Knowledge Engine`);
  lines.push(`total_bridges_analyzed: ${context.total_bridges}`);
  lines.push(`evidence_status: ${context.evidence_sufficient ? 'verified' : 'sparse'}`);
  lines.push('---');
  lines.push('');

  // Заголовок
  lines.push(`# Cross-Domain Analysis: ${context.domain_a} ↔ ${context.domain_b}`);
  lines.push('');

  // Основной синтез
  if (synthesis?.summary) {
    lines.push('## Core Synthesis');
    lines.push(synthesis.summary.trim());
    lines.push('');
  }

  // Ключевые мосты
  lines.push(`## Key Bridges (${context.top_bridges.length})`);
  lines.push('');

  context.top_bridges.forEach((bridge: CrossDomainBridgeItem, index: number) => {
    lines.push(
      `### ${index + 1}. [${bridge.source_claim.domain}] ${bridge.source_claim.content.slice(0, 60)}... ↔ [${bridge.target_claim.domain}] ${bridge.target_claim.content.slice(0, 60)}...`
    );
    lines.push(`- **Relation:** \`${bridge.relation_type}\` (Strength: ${bridge.strength.toFixed(2)}, Evidence Score: ${bridge.evidence_score.toFixed(2)})`);

    // Если есть сгенерированное объяснение для конкретного моста
    const explanation = synthesis?.bridgeExplanations?.[bridge.bridge_id];
    if (explanation) {
      lines.push('');
      lines.push(explanation.trim());
    }

    // Блок доказательной базы и происхождения
    lines.push('');
    lines.push('**Evidence & Provenance:**');
    lines.push(
      `- **Claim A (${bridge.source_claim.domain}):** "${bridge.source_claim.content}"`
    );
    lines.push(
      `  - *Source:* [[${bridge.source_claim.source_title}]] (ID: \`${bridge.source_claim.source_id}\`)`
    );
    lines.push(
      `- **Claim B (${bridge.target_claim.domain}):** "${bridge.target_claim.content}"`
    );
    lines.push(
      `  - *Source:* [[${bridge.target_claim.source_title}]] (ID: \`${bridge.target_claim.source_id}\`)`
    );

    if (bridge.supporting_snippet) {
      lines.push('');
      lines.push('> [!INFO] Supporting Snippet');
      lines.push(`> ${bridge.supporting_snippet.replace(/\n/g, '\n> ')}`);
    }

    lines.push('');
  });

  // Практические выводы
  if (synthesis?.practicalImplications && synthesis.practicalImplications.length > 0) {
    lines.push('## Practical Implications');
    synthesis.practicalImplications.forEach((imp) => {
      lines.push(`- ${imp}`);
    });
    lines.push('');
  }

  // Список первоисточников
  lines.push('## Referenced Sources');
  uniqueSources.forEach((title, id) => {
    lines.push(`- [[${title}]] \`#id:${id}\``);
  });
  lines.push('');

  lines.push('---');
  lines.push('*Generated by Personal Knowledge Agent (PKA)*');

  return lines.join('\n');
}

export async function copyToClipboard(text: string): Promise<boolean> {
  try {
    await navigator.clipboard.writeText(text);
    return true;
  } catch (err) {
    console.error('Failed to copy text to clipboard:', err);
    return false;
  }
}

export function downloadMarkdownFile(filename: string, content: string): void {
  const blob = new Blob([content], { type: 'text/markdown;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.setAttribute('download', filename.endsWith('.md') ? filename : `${filename}.md`);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
